/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt
 * to change this license Click
 * nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this
 * template
 */
package ccori.uni.pdv;

/**
 *
 * @author devCcori
 */

import ccori.uni.dbUtils.pdvUtils;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;
import javax.swing.JTextField;

public class PdV_Main extends javax.swing.JFrame {

  /**
   * Creates new form PdV_Main
   */
  public PdV_Main() {
    initComponents();
    actualizarHora();
    setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    addWindowListener(new WindowAdapter() {
      @Override
      public void windowClosing(WindowEvent e) {
        dispose();
      }
    });
  }

  public JTextField getjTextField1() { return jTextField1; }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jTextField2 = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jTextField5 = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    labelHora = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox<>();
    jComboBox2 = new javax.swing.JComboBox<>();
    jLabel7 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1 = new javax.swing.JTable();
    jLabel5 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jLabel10 = new javax.swing.JLabel();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jButton3 = new javax.swing.JButton();
    jButton4 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setText("ID Trabajador");

    jLabel2.setText("DNI Cliente");

    jLabel3.setText("Tipo de comprobante");

    jLabel6.setText("Tipo de pago");

    jLabel4.setText("Codigo de pedido");

    try {
      Integer cantVentas = pdvUtils.getRowCount() + 1;
      jTextField5.setText(cantVentas.toString());
    } catch (SQLException e) {
      jTextField5.setText("0Error");
      System.out.println("Error al obtener el numero de ventas");
    }

    labelHora.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    labelHora.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    labelHora.setText("jLabel5");

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] {"Item 1", "Item 2", "Item 3", "Item 4"}));

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(
        new String[] {"Item 1", "Item 2", "Item 3", "Item 4"}));

    jLabel7.setText("Productos");

    jButton1.setText("-");

    jButton2.setText("+");

    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object[][] {},
        new String[] {"Producto", "Cantidad", "Precio Unitario", "Subtotal"}) {
      Class[] types =
          new Class[] {java.lang.String.class, java.lang.Double.class,
                       java.lang.Double.class, java.lang.Double.class};

      @Override
      public Class getColumnClass(int columnIndex) {
        return types[columnIndex];
      }
    });
    jScrollPane1.setViewportView(jTable1);

    jLabel5.setText("IMPORTE");

    jLabel8.setText(" ");

    jLabel9.setText("IGV");

    jLabel10.setText(" ");

    jLabel11.setText("TOTAL");

    jLabel12.setText(" ");

    jButton3.setText("CANCELAR PAGO");
    jButton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton3ActionPerformed(evt);
      }
    });

    jButton4.setText("GENERAR PAGO");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton4ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout =
        new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(
                                layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(
                                        jComboBox2,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        222,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(
                                layout
                                    .createParallelGroup(
                                        javax.swing.GroupLayout.Alignment
                                            .TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment
                                                  .LEADING,
                                              layout.createSequentialGroup()
                                                  .addComponent(jLabel3)
                                                  .addGap(18, 18, 18)
                                                  .addComponent(
                                                      jComboBox1,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      222,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                                  .addComponent(jLabel1)
                                                  .addGap(18, 18, 18)
                                                  .addComponent(
                                                      jTextField1,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      222,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                                  .addComponent(jLabel2)
                                                  .addGap(18, 18, 18)
                                                  .addComponent(
                                                      jTextField2,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      222,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE))
                                    .addGroup(
                                        javax.swing.GroupLayout.Alignment
                                            .LEADING,
                                        layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(
                                                javax.swing.LayoutStyle
                                                    .ComponentPlacement
                                                    .UNRELATED)
                                            .addComponent(
                                                jButton2,
                                                javax.swing.GroupLayout
                                                    .PREFERRED_SIZE,
                                                39,
                                                javax.swing.GroupLayout
                                                    .PREFERRED_SIZE)
                                            .addPreferredGap(
                                                javax.swing.LayoutStyle
                                                    .ComponentPlacement.RELATED)
                                            .addComponent(
                                                jButton1,
                                                javax.swing.GroupLayout
                                                    .PREFERRED_SIZE,
                                                39,
                                                javax.swing.GroupLayout
                                                    .PREFERRED_SIZE))))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48,
                        Short.MAX_VALUE)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(
                                        jTextField5,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        154,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(
                                labelHora,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 263,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                          .addContainerGap()
                          .addComponent(jScrollPane1)
                          .addContainerGap())
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                     Short.MAX_VALUE)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup()
                                    .addGroup(layout
                                                  .createParallelGroup(
                                                      javax.swing.GroupLayout
                                                          .Alignment.LEADING)
                                                  .addComponent(jLabel11)
                                                  .addComponent(jLabel9)
                                                  .addComponent(jLabel5))
                                    .addGroup(
                                        layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout
                                                    .Alignment.LEADING)
                                            .addGroup(
                                                javax.swing.GroupLayout
                                                    .Alignment.TRAILING,
                                                layout.createSequentialGroup()
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle
                                                            .ComponentPlacement
                                                            .RELATED)
                                                    .addComponent(jLabel12))
                                            .addGroup(
                                                layout.createSequentialGroup()
                                                    .addGap(64, 64, 64)
                                                    .addGroup(
                                                        layout
                                                            .createParallelGroup(
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .Alignment
                                                                    .LEADING)
                                                            .addComponent(
                                                                jLabel8)
                                                            .addComponent(
                                                                jLabel10,
                                                                javax.swing
                                                                    .GroupLayout
                                                                    .Alignment
                                                                    .TRAILING))))
                                    .addGap(44, 44, 44))
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup()
                                    .addComponent(jButton3)
                                    .addGap(157, 157, 157))))
            .addGroup(layout
                          .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING)
                          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                    layout.createSequentialGroup()
                                        .addContainerGap(567, Short.MAX_VALUE)
                                        .addComponent(jButton4)
                                        .addGap(34, 34, 34))));
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(
                                jTextField1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(
                                jTextField5,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                layout.createSequentialGroup()
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle
                                            .ComponentPlacement.UNRELATED)
                                    .addGroup(layout
                                                  .createParallelGroup(
                                                      javax.swing.GroupLayout
                                                          .Alignment.BASELINE)
                                                  .addComponent(jLabel2)
                                                  .addComponent(
                                                      jTextField2,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE))
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle
                                            .ComponentPlacement.UNRELATED)
                                    .addGroup(layout
                                                  .createParallelGroup(
                                                      javax.swing.GroupLayout
                                                          .Alignment.BASELINE)
                                                  .addComponent(jLabel3)
                                                  .addComponent(
                                                      jComboBox1,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE,
                                                      javax.swing.GroupLayout
                                                          .DEFAULT_SIZE,
                                                      javax.swing.GroupLayout
                                                          .PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                          .addGap(29, 29, 29)
                                          .addComponent(labelHora,
                                                        javax.swing.GroupLayout
                                                            .PREFERRED_SIZE,
                                                        43,
                                                        javax.swing.GroupLayout
                                                            .PREFERRED_SIZE)))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(
                                jComboBox2,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1,
                                  javax.swing.GroupLayout.PREFERRED_SIZE,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        layout
                            .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7,
                        Short.MAX_VALUE)
                    .addComponent(jButton3)
                    .addContainerGap())
            .addGroup(layout
                          .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING)
                          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                    layout.createSequentialGroup()
                                        .addContainerGap(701, Short.MAX_VALUE)
                                        .addComponent(jButton4)
                                        .addContainerGap())));

    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void
  jButton3ActionPerformed(java.awt.event.ActionEvent
                              evt) { // GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_jButton3ActionPerformed

  private void
  jButton4ActionPerformed(java.awt.event.ActionEvent
                              evt) { // GEN-FIRST:event_jButton4ActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_jButton4ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    //(optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info :
           javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(PdV_Main.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(PdV_Main.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(PdV_Main.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(PdV_Main.class.getName())
          .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() { new PdV_Main().setVisible(true); }
    });
  }

  // define una funcion actualizarHora() que actualize el labelHora cada
  // segundo:
  public final void actualizarHora() {
    Timer timer =
        new Timer("HoraActualizada");  // Crea un timer y le asigna un nombre
    TimerTask task = new TimerTask() { // Crea una tarea para el timer
      @Override
      public void run() {
        labelHora.setText(
            new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date()));
      }
    };
    timer.schedule(
        task, 0,
        1000); // Asigna la tarea al timer y lo ejecuta cada 1000 milisegundos
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JButton jButton3;
  private javax.swing.JButton jButton4;
  private javax.swing.JComboBox<String> jComboBox1;
  private javax.swing.JComboBox<String> jComboBox2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JTextField jTextField2;
  private javax.swing.JTextField jTextField5;
  private javax.swing.JLabel labelHora;
  // End of variables declaration//GEN-END:variables
}
